version: '3'
services:
    db:
        restart: always
        build: ./docker/mysql
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_ROOT_HOST: '%'
    app:
        restart: always
        build: ./docker/java
        ports:
            - 18080:18080
        environment:
            db_ip: db
            db_port: 3306
            db_user: root
            db_pd: admin123
        links:
          - db
        depends_on:
          - db
